### ISSUE TITLE
Submodule not fetching

### ISSUE THREAD

**Issue by leoujz** [ddemidov/mba#2]
git clone --recursive

or

git clone
git submodule update --init

gives error message:

Fetched in submodule path 'python/pybind11', but it did not contain 2f418d2b87c26334f2b1799535baf5be09cb686d. Direct fetching of that commit failed.

**Comment by ddemidov** [comment]
Is this related to #3?

**Comment by leoujz** [comment]
this is not related to #3 , because I configured my SSH when I met the error "Direct fetching of that commit failed". 
I also checked the log of pybind/pybind11, the commit 2f418d2b87c26334f2b1799535baf5be09cb686d does not exist.
Also, I manually cloned the pybind11 repository, and it compiles successfully

**Comment by ddemidov** [comment]
Ah, this was a leftover in my local repo since the time pybind11 was hosted under its author's account. Should be fixed now, thanks again!
