### ISSUE TITLE
Quadrants visible in interpolation result

### ISSUE THREAD

**Issue by jmswaney** [ddemidov/mba#5]
Going through the python example, I noticed that the interpolated surface has 4 clearly distinguished quadrants. I thought the cubic splines would smoothly transition between the control point grid, so I'm confused why these quadrants are so apparent. Am I missing something?

**Comment by ddemidov** [comment]
Can you be more specific (what cell in the python example)? I don't see any quadrant boundaries there. Could those be pixels on the surface plots?

**Comment by jmswaney** [comment]
In the cell where plot_surface is called the pcolor plot looks like it’s split at x = 0.5 and y = 0.5. The quadrants are much bigger than one of the pixels

On Jun 27, 2018, at 11:13 AM, Denis Demidov <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you be more specific (what cell in the python example)? I don't see any quadrant boundaries there. Could those be pixels on the surface plots?

**Comment by ddemidov** [comment]
Are you looking at the notebook [hosted on jupyter.org](http://nbviewer.jupyter.org/github/ddemidov/mba/blob/master/python/example.ipynb), or do you run the example yourself? Here is what I see in the hosted notebook:

![download](https://user-images.githubusercontent.com/270503/41983947-13c359ce-7a38-11e8-91b1-c98ae823945e.png)

The surfaces look rather smooth to me.

**Comment by ddemidov** [comment]
Hmm, I just tried to rerun the example, and here is what I see now:

![download 1](https://user-images.githubusercontent.com/270503/41984248-e4fbc3e6-7a38-11e8-82ac-dfcb79ae09e4.png)

Is this what you see as well? This is clearly a bug, I'll try to look into it.

**Comment by jmswaney** [comment]
Yeah that's what I'm getting. When I look at the notebook on github it looks great, but I get those quadrants when I run it locally.

**Comment by ddemidov** [comment]
git bisect points to f55707a44bf9b93c858e15a31a6fb9fcfdbb0e29 as the first bad commit, but I can not yet see what is wrong with that. The commit mostly updates pybind11 and resolves a resulting issue.

**Comment by ddemidov** [comment]
It looks like this was a data layout issue with numpy. transpose() changes strides of the array, but does not touch the actual data layout. It looks like at some point pybind11 stopped making copies of the arrays, which made this bug visible. `copy()` after `transpose()` fixes the issue for me.

Thank you for reporting!

**Comment by ddemidov** [comment]
To clarify, the fix is contained within cell [3] of the notebook.

**Comment by ddemidov** [comment]
And of course I forgot to update the notebook in the source tree (sorry, coding while on vacation). 8203404 takes care of that.

**Comment by jmswaney** [comment]
Great, it's working for me now. Thanks!
